# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wtorwold <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/01 15:11:11 by wtorwold          #+#    #+#              #
#    Updated: 2018/10/04 20:15:06 by wtorwold         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

PRG = ft_display_file

NAME = ft_display_file.c

OUT = a.out

all:
	gcc -Wall -Wextra -Werror $(NAME) -o $(PRG)

clean:
	/bin/rm -f $(PRG)

fclean: clean
	/bin/rm -f $(PRG)

re: fclean all
